### PR TITLE
adding seperate files to compile on IBM Power and Z

### PR DESCRIPTION
**Pull request by brahmaroutu**
Signed-off-by: Srini Brahmaroutu <srbrahma@us.ibm.com>

### CODE REVIEW

**Comment by benbjohnson** [comment]
@brahmaroutu It looks the values are copied from a 32-bit arch. Does `ppc64le` and `s390x` support a 64-bit address space? Would the values in `bolt_amd64.go` be a better fit?

**Comment by brahmaroutu** [comment]
@benbjohnson Thanks for the tip/suggestion. I have updated the files and also added build tags. Thanks for reviewing.

**Comment by brahmaroutu** [comment]
@benbjohnson Please review and merge this PR, I am waiting for this functionality to build Docker on Power and Z.

**Comment by benbjohnson** [comment]
@brahmaroutu Sorry, i thought this was already merged. Merging now.

**Comment by brahmaroutu** [comment]
Awesome. Thanks a lot @benbjohnson

**Pull request merged**
