### PR TITLE
bucket: document Put() value must remain valid for the transaction

### PR DESCRIPTION
**Pull request by pmezard**
Issue #324

I have been bitten by this too. Let's try to move forward on the documentation (or implementation).

### CODE REVIEW

**Comment by DavidVorick** [comment]
What is meant by 'supplied value must remain vaild for the transaction'?

We're experiencing bugs, maybe this is the source of our bugs?

**Comment by pmezard** [comment]
It means the "value" parameter is held by the transaction and will be evaluated at Commit() time. See the bug referenced above for details.

**Comment by benbjohnson** [comment]
I think it's probably worth copying the value byte slice on `Put()`. Then it would be consistent with the key. Also, it's unlikely to have a high overhead compared to the overhead of writing pages to disk.

Can you PR the copy() change instead?

**Comment by MJDSys** [comment]
@benbjohnson I doubt the copy would cost much, but I would worry that this would cause large amounts of garbage to be generated.  If we are going to move to copying both, could the sync.Pool be used?  And/Or create a second function the explicitly does no copy?

I've been playing a test in Bolt, to see about speeding it up, and I noticed that it has a large amount of CPU time dealing with the allocator/GC.  And other programs using local K/V stores often suffer this too.  So this isn't theoretical, and a huge plus to not run into.  Of course safe behaviour is always more important too :)

**Comment by DavidVorick** [comment]
I'm in full support of safe behavior first, performance second. Right now it seems like bolt has a lot of unintuitive and not-well documented 'gotcha's - we've been bitten by a handful. I'm wondering if the issue I have open right now (#429) isn't somehow related to this.

**Comment by benbjohnson** [comment]
@MJDSys I agree that the extra GC sucks. I could _maybe_ see a "NoCopy" flag on the `Bucket` if there's profiling data to support a case for a significant performance gain. A lot of people (myself included) encode/decode to and from the `value` byte slice so that's already doing a copy.

@pmezard @DavidVorick I went ahead and posted a PR for this fix: #443. Can you test it out locally to sanity check it?

**Comment by MJDSys** [comment]
@benbjohnson I have seen profiling data saying that copying data in the database layer is expensive, due to GCs.  The only bolt related application I've seen do this is a test in your suite.  I know syncthing has significant CPU usage for me using leveldb, a large amount of which is spent in the GC.  So if you are doing many writes this can become a problem, and thus why I suggest avoiding it.

I agree a safe by default option is best, so only people who have write loads high enough to cause issues need to worry.  If you are happy to take such a flag in the future, should someone need it, I agree going safe first is best.

**Comment by pmezard** [comment]
Replaced by https://github.com/boltdb/bolt/pull/443

**Comment by DavidVorick** [comment]
@benbjohnson ran the PR on our test suite. Did not fix #429, but also did not cause noticeable slowdown.

**Comment by pmezard** [comment]
Reopening documentation fix after code fix was rejected.

**Comment by benbjohnson** [comment]
:+1:

**Comment by pmezard** [comment]
@benbjohnson maybe close https://github.com/boltdb/bolt/issues/324

**Comment by benbjohnson** [comment]
Thanks!

**Pull request merged**
