### PR TITLE
Multiple doc fixes

### PR DESCRIPTION
**Pull request by hvnsweeting**

### CODE REVIEW

**Comment by chrsm** [comment]
I don't think the singular bit makes the documentation any more clear. Plural is perfectly understandable in this context.

**Comment by otoolep** [comment]
Agreed, singular doesn't make sense to me either.

**Comment by benbjohnson** [comment]
@hvnsweeting I agree about the plural. I'll accept the fix for changing `trade offs` to `trade-offs` if you want change the commit.

**Comment by benbjohnson** [comment]
Cherry picked 0671704: https://github.com/boltdb/bolt/commit/40aeece0921529a7a3c0113a4435c583b87227db

**Pull request closed without merging**
