### PR TITLE
enhc: update example for nested buckets

### PR DESCRIPTION
**Pull request by jaredfolkins**
After our conversation here is a better example for nested buckets.

### CODE REVIEW

**Comment by benbjohnson** [comment]
@jaredfolkins Thanks for the PR! I looked through it and I think you can simplify if you assume the account bucket has already been created. What about something like this:

```go
// createUser creates a new user in the given account.
func createUser(accountID int, u *User) error {
	// Start the transaction.
	tx, err := db.Begin(true)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	// Retrieve the root bucket for the account.
	// Assume this has already been created when the account was set up.
	root := tx.Bucket([]byte(strconv.FormatUint(accountID, 10)))
	
	// Setup the users bucket.
	bkt, err := root.CreateBucketIfNotExists([]byte("USERS"))
	if err != nil {
		return err
	}

	// Generate an ID for the new user.
	userID, err := bkt.NextSequence()
	if err != nil {
		return err
	}
	u.ID = userID

	// Marshal and save the encoded user.
	if buf, err := json.Marshal(u); err != nil {
		return err
	} else if err := bkt.Put([]byte(strconv.FormatUint(u.ID, 10)), buf); err != nil {
		return err
	}

	// Commit the transaction.
	if err := tx.Commit(); err != nil {
		return err
	}

	return nil
}
```

**Comment by jaredfolkins** [comment]
Updated with your example.

**Comment by benbjohnson** [comment]
Thanks, Jared!

**Comment by jaredfolkins** [comment]
Hah! It is I who should say thanks. I really appreciate you and the gift to of your time and expertise to the community. Take care.

**Pull request merged**
