### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by asdine**
Adding an ORM helper

### CODE REVIEW

**Comment by benbjohnson** [comment]
@asdine Sorry, I'm not sure how I missed this PR. If you want to reopen it I'll merge it in.

**Comment by asdine** [comment]
No problem! If you don't mind i will reopen it later (maybe this week) because i'm not satisfied with my current implementation and would like to clean up my code a little bit.

**Comment by asdine** [comment]
It is better now :)

**Comment by benbjohnson** [comment]
@asdine Sorry, I merged an earlier PR that changed a line at the same spot. Can you rebase and update the PR and then I can merge.

**Comment by asdine** [comment]
Done

**Comment by benbjohnson** [comment]
Awesome, thanks!

**Comment by asdine** [comment]
Thanks!

**Pull request merged**
