### PR TITLE
Speedup open huge file

### PR DESCRIPTION
**Pull request by funny-falcon**
Couple of improvements on reading huge file metadata (freelist):

- preallocate cache hash
- use custom quicksort for pgids cause sort.Sort is overkill on integer array
- recheck, if pgids already sorted

### CODE REVIEW

**Comment by funny-falcon** [comment]
Looks like it should fix #406

**Comment by cep21** [comment]
Do these changes show any improvement on ```go test -bench``` results?

**Comment by funny-falcon** [comment]
I've not tested with `go test -bench`. I'll do it tomorrow, if you wish.

I've tested with custom script which repeatedly opens huge (256Mb) file, reads dozen of rows and then closes it. I profiled it with `runtime/pprof` - that is how I found what to fix, and how i measure improvements.

'Cosmetic' change doesn't improve much, but i think it will on larger file, since it lets use less stack frames for searching.

Other changes greatly improves database open time, and perhaps general performance.

#407 also improves open time in read-write mode.

**Comment by funny-falcon** [comment]
I've tested with files in /dev/shm (cause i have no SSD):
````
$ go test -run sort -bench . 2>&1 | tee master.test                                                                                                                                      
seed: 56837
quick settings: count=5, items=1000, ksize=1024, vsize=1024
PASS
Benchmark_FreelistRelease10K       30000             51473 ns/op
Benchmark_FreelistRelease100K      10000            179537 ns/op
Benchmark_FreelistRelease1000K       500           3218242 ns/op
Benchmark_FreelistRelease10000K       50          35683196 ns/op
BenchmarkDBBatchAutomatic            300           4776553 ns/op
BenchmarkDBBatchSingle        20          71448729 ns/op
BenchmarkDBBatchManual10x100         500           3289631 ns/op
ok      github.com/boltdb/bolt  20.960s

$ go test -run sort -bench . 2>&1 | tee speed.test                                                                                                                                       
seed: 8899
quick settings: count=5, items=1000, ksize=1024, vsize=1024
PASS
Benchmark_FreelistRelease10K       30000             50469 ns/op
Benchmark_FreelistRelease100K      10000            164939 ns/op
Benchmark_FreelistRelease1000K       500           3063584 ns/op
Benchmark_FreelistRelease10000K       50          33487644 ns/op
BenchmarkDBBatchAutomatic            300           4800126 ns/op
BenchmarkDBBatchSingle        20          67751109 ns/op
BenchmarkDBBatchManual10x100         500           3173357 ns/op
ok      github.com/boltdb/bolt  15.772s

$ benchcmp master.test speed.test                                                                                                                                                        
benchmark                           old ns/op     new ns/op     delta
Benchmark_FreelistRelease10K        51473         50469         -1.95%
Benchmark_FreelistRelease100K       179537        164939        -8.13%
Benchmark_FreelistRelease1000K      3218242       3063584       -4.81%
Benchmark_FreelistRelease10000K     35683196      33487644      -6.15%
BenchmarkDBBatchAutomatic           4776553       4800126       +0.49%
BenchmarkDBBatchSingle              71448729      67751109      -5.18%
BenchmarkDBBatchManual10x100        3289631       3173357       -3.53%
````

**Comment by cep21** [comment]
AWS SSD c3.2xlarge
```
benchmark                           old ns/op      new ns/op      delta
Benchmark_FreelistRelease10K        54766          58860          +7.48%
Benchmark_FreelistRelease100K       215355         187160         -13.09%
Benchmark_FreelistRelease1000K      2751506        2329097        -15.35%
Benchmark_FreelistRelease10000K     48035305       41385433       -13.84%
BenchmarkDBBatchAutomatic           6859916        6543817        -4.61%
BenchmarkDBBatchSingle              1093182193     1011586289     -7.46%
BenchmarkDBBatchManual10x100        13231862       12882315       -2.64%

benchmark                           old allocs     new allocs     delta
Benchmark_FreelistRelease10K        6              5              -16.67%
Benchmark_FreelistRelease100K       6              5              -16.67%
Benchmark_FreelistRelease1000K      6              5              -16.67%
Benchmark_FreelistRelease10000K     6              5              -16.67%
BenchmarkDBBatchAutomatic           14356          14649          +2.04%
BenchmarkDBBatchSingle              64997          62990          -3.09%
BenchmarkDBBatchManual10x100        8062           8042           -0.25%

benchmark                           old bytes     new bytes     delta
Benchmark_FreelistRelease10K        82544         82512         -0.04%
Benchmark_FreelistRelease100K       805280        805248        -0.00%
Benchmark_FreelistRelease1000K      8049056       8049024       -0.00%
Benchmark_FreelistRelease10000K     80413088      80413056      -0.00%
BenchmarkDBBatchAutomatic           547246        566053        +3.44%
BenchmarkDBBatchSingle              37907168      35822093      -5.50%
BenchmarkDBBatchManual10x100        1414942       1414317       -0.04%

```

**Comment by funny-falcon** [comment]
final results on my machine:
````
$ benchcmp master.test speed6.test
benchmark                           old ns/op     new ns/op     delta
Benchmark_FreelistRelease10K        56395         48481         -14.03%
Benchmark_FreelistRelease100K       183334        149627        -18.39%
Benchmark_FreelistRelease1000K      3234908       2848532       -11.94%
Benchmark_FreelistRelease10000K     35556600      30420762      -14.44%
BenchmarkDBBatchAutomatic           4551503       4419403       -2.90%
BenchmarkDBBatchSingle              70781520      68206906      -3.64%
BenchmarkDBBatchManual10x100        3274355       3177992       -2.94%

benchmark                           old allocs     new allocs     delta
Benchmark_FreelistRelease10K        6              5              -16.67%
Benchmark_FreelistRelease100K       6              5              -16.67%
Benchmark_FreelistRelease1000K      6              5              -16.67%
Benchmark_FreelistRelease10000K     6              5              -16.67%
BenchmarkDBBatchAutomatic           15033          15036          +0.02%
BenchmarkDBBatchSingle              63078          61078          -3.17%
BenchmarkDBBatchManual10x100        8048           8028           -0.25%

benchmark                           old bytes     new bytes     delta
Benchmark_FreelistRelease10K        82544         82512         -0.04%
Benchmark_FreelistRelease100K       805280        805248        -0.00%
Benchmark_FreelistRelease1000K      8049056       8049024       -0.00%
Benchmark_FreelistRelease10000K     80413088      80413056      -0.00%
BenchmarkDBBatchAutomatic           590069        590287        +0.04%
BenchmarkDBBatchSingle              32325973      32261991      -0.20%
BenchmarkDBBatchManual10x100        1413850       1413191       -0.05%
````

**Comment by funny-falcon** [comment]
Looks like i should not mess with so many changes in one commit.
More over: now I doubt that sorting performance really matters.

**Pull request closed without merging**
