### PR TITLE
Revert "replace unix implementation to be the same as solaris to fix …"

### PR DESCRIPTION
**Pull request by benbjohnson**
Reverts a previous commit based on feedback from https://github.com/boltdb/bolt/issues/653#issuecomment-276383239.

/cc @schollz

### CODE REVIEW

**Comment by schollz** [comment]
Thanks, it seems to fix the problem. I will check the ARM systems later and let you know.

**Comment by benbjohnson** [comment]
@schollz Thank you. Once you can test the ARM version then I'll merge it in.

**Comment by schollz** [comment]
@benbjohnson Tested and it works well on ARM. Thanks again for the quick response and also bringing my attention to great utility of `git bisect`!

**Comment by benbjohnson** [comment]
I am surprised that it's that commit that's causing the issue. Let me know if you have any further issues.

**Pull request merged**
