### PR TITLE
use sync.Pool for allocating small pages

### PR DESCRIPTION
**Pull request by funny-falcon**

### CODE REVIEW

**Comment by benbjohnson** [comment]
Do you have benchmarks or memory profiles for this change?

**Comment by funny-falcon** [comment]
I've added "-path" flag in db_test.go to specify where temporary db should be allocated.
I tested in '/dev/shm' (ie in-memory) cause I don't have SSD disk.
I get following times of `GOMAXPROCS=1 go test -path=/dev/shm`:
````
Go 1.4
before
ok      github.com/boltdb/bolt  195.516s
after
ok      github.com/boltdb/bolt  142.697s

Go 1.5
before
ok      github.com/boltdb/bolt  87.658s
after
ok      github.com/boltdb/bolt  79.913s
````
Go 1.5 really has much better GC collector. But sync.Pool helps here too.

Note, that sync.Pool plays well with GC: it is cleared before GC cycle. So that it can only decrease memory consumption, not increase.

**Comment by funny-falcon** [comment]
It will also help when there is many open small bolt databases: then their page buffers will be reused between them.

**Comment by LK4D4** [comment]
@benbjohnson I encountered this recently in Docker project. Using sync.Pool could help performance because of fewer allocations and also prevent too often GC collection. I don't see a drawback in this. Should we try again?
@funny-falcon are you still interested in this change?

**Comment by benbjohnson** [comment]
I am interested in integrating sync.Pool but I want to get longer running integration tests and multi-platform CI running first.

**Comment by funny-falcon** [comment]
Close in favor of #501

**Pull request closed without merging**
