### PR TITLE
add option to skip freelist sync

### PR DESCRIPTION
**Pull request by xiang90**
When the database has a lot of freepages, the cost to sync all
freepages down to disk is high. If the total database size is
small (<10GB), and the application can tolerate ~10 seconds
recovery time, then it is reasonable to simply not sync freelist
and rescan the db to rebuild freelist on recovery.

This is a early attempt. Would like to see your feedbacks.

/cc @benbjohnson @heyitsanthony

### CODE REVIEW

**Comment by xiang90** [comment]
In our test environment, this reduces the db size from ~100MB to ~10MB and reduce 5x iops.

**Comment by lrita** [comment]
In my opinion, this is a good idea to reduce IOPS. But, this implement maybe cause database corruption for now, if there are some k-v pairs' length large than a pagesize. `page. overflow` is relation to this problem.

```
type page struct {
	id       pgid
	flags    uint16
	count    uint16
	overflow uint32
	ptr      uintptr
}
```

**Comment by xiang90** [comment]
@lrita fixed.

**Comment by xiang90** [comment]
talked with @benbjohnson and confirmed this will not get merged. so closing.

**Pull request closed without merging**
