### PR TITLE
Skip empty pages during cursor seek

### LINKED ISSUE #429: Boltdb Deleting Bucket?
I've started poking around in the bolt codebase, but it seems like, nondeterministically, though after a significant amount of changes within a single tx, calling `Delete` on a bucket can result in the entire bucket being deleted.

edit: it doesn't always drop the whole bucket. Sometimes calling `delete` will just drop 3/5 items. Maybe it's getting confused about a leaf node vs. root/branch node and dropping a bunch of children?

edit2: inside of `Bucket.Delete`, a call to `c.node().del(key)` is made. Seems like the failure only occurs when the index of the leaf is `0` and len(node.inodes) is `1`. Further testing continues to confirm this trend.

Things I know about my code:

1. A _lot_ is happening in a single tx. Probably on the order of thousands of reads and writes to the bucket.
2. The change that is causing the bucket to be emptied is not happening inside of a ForEach statement or a cursor.
3. The bucket seems most likely to wipe when there are only a few elements remaining. The stress test brings it up as high as 50 items, but it usually fails at 2 or 3 items. ~~I haven't seen it fail with more than 6 items remaining in the bucket.~~ (got it to drop from 18 to 10 items in a single delete operation by increasing the stress)
4. The failure is nondeterministic. Sometimes there won't be a failure, but I can get the failure happening again by adding printlns in arbitrary places in my code (the logic is not changed at all, but it can have an effect on whether the test fails or not)
```
    lenScoBucket(tx) // prints 3
    err := scoBucket.Delete(id[:]) // err is nil
    lenScoBucket(tx) // prints 0
```

My whole codebase is pretty complicated. It's completely possible that I'm doing something else incorrect somewhere but the error isn't showing up until this point. I will be digging through the bolt code, but was hoping someone had ideas.

### PR DESCRIPTION
**Pull request by benbjohnson**
## Overview

This commit fixes an issue where keys are skipped by cursors after deletions occur in a bucket. This occurred because the cursor seeks to the leaf page but does not check if it is empty.

Fixes #429, #450

---

@lukechampine Thanks for digging into this and figuring it out. The fix you made makes sense. The cursor needs to move forward to the next item if an empty page is found. I made a small tweak to the fix inside `next()` so that it doesn't recursively call itself. I also added a test case to check for it. I added you as the commit author, though, for attribution.

Can you take a look and verify that this fix works for you in your project?

### CODE REVIEW

**Comment by DavidVorick** [comment]
This PR passes all of our unit tests, which the master branch does not do. I'm doing a much more thorough test right now involving our pre-production system, usually takes a while but I'll report back when that finishes.

**Comment by lukechampine** [comment]
Thanks for getting to the bottom of this. Without a solid understanding of bolt's internals, my fixes were a shot in the dark. It was driving me a little crazy, haha.
I am a little surprised that this hasn't caused issues for anyone else. Maybe using `ForEach` after deletions is a rare use case. Does your new test case replicate the issue deterministically?

**Comment by benbjohnson** [comment]
@DavidVorick Awesome! let me know how the rest of the testing goes.

@lukechampine Your fix was pretty spot on. I think most people don't have a need to delete multiple items and then read them from a bucket in the same transaction. Many times mutation and data retrieval occur in separate transactions.

The test case seems to be deterministic. Writing 1000 keys ensures that it'll cover multiple pages and then deleting a large contiguous block at the beginning ensures that the first leaf page will be empty.

**Comment by DavidVorick** [comment]
@benbjohnson rest of testing has gone well. I appreciate you writing this, seems to have solved a frustrating bug

**Comment by benbjohnson** [comment]
@DavidVorick awesome, thanks for testing it out. Just merged. :+1:

**Pull request merged**
