### PR TITLE
Raise maxMapSize from 256MB to 2GB on 386, arm.

### LINKED ISSUE #260: Cursor behavor on modifications
Hello.

https://gist.github.com/freepk/b4bfb0aacbc6e2a5f862

There are many situations when cursor's Prev() Next() don't return correct position or error after data change.
In this example cursor position after Seek is "testKey00". After delete "testKey00" and "testKey01", Next() return nil, but Prev() return "testKey02" how to understan this behavior?

### PR DESCRIPTION
**Pull request by tgulacsi**
Fixes #260 and #277.

### CODE REVIEW

**Comment by fern4lvarez** [comment]
You mentioned that compilation failed when trying to enlarge this value. What was the issue and how did you overcome it?

**Comment by tgulacsi** [comment]
I've tried the noob way: append F, then 0 to the constant.
The problem is with the high end: only 7 is allowed (2^32-1).

**Comment by benbjohnson** [comment]
@tgulacsi Thanks! I added a check in the `mmap()` function to ensure Bolt doesn't try to grow beyond the max. Can you try this and see if it gives you an error (instead of a panic) when the max size is back at 256MB?

```go
// mmap opens the underlying memory-mapped file and initializes the meta references.
// minsz is the minimum size that the new mmap can be.
func (db *DB) mmap(minsz int) error {
	db.mmaplock.Lock()
	defer db.mmaplock.Unlock()

	info, err := db.file.Stat()
	if err != nil {
		return fmt.Errorf("mmap stat error: %s", err)
	} else if int(info.Size()) < db.pageSize*2 {
		return fmt.Errorf("file size too small")
	}

	// Ensure the size is at least the minimum size.
	var size = int(info.Size())
	if size < minsz {
		size = minsz
	}
	size = db.mmapSize(size)

	// Verify the map size is not above the maximum allowed.
	if size > maxMapSize {
		return fmt.Errorf("mmap too large")
	}

	// Dereference all mmap references before unmapping.
	if db.rwtx != nil {
		db.rwtx.root.dereference()
	}

	// Unmap existing data before continuing.
	if err := db.munmap(); err != nil {
		return err
	}

	// Memory-map the data file as a byte slice.
	if err := mmap(db, size); err != nil {
		return err
	}

	// Save references to the meta pages.
	db.meta0 = db.page(0).meta()
	db.meta1 = db.page(1).meta()

	// Validate the meta pages.
	if err := db.meta0.validate(); err != nil {
		return fmt.Errorf("meta0 error: %s", err)
	}
	if err := db.meta1.validate(); err != nil {
		return fmt.Errorf("meta1 error: %s", err)
	}

	return nil
}
```

**Comment by tgulacsi** [comment]
Yes, this change prevents creating an unreadable .boltdb, and returns "mmap allocate error: mmap too large".
So LGTM.

**Comment by benbjohnson** [comment]
Awesome. Thanks for checking that and thanks for bumping the max size to 2GB. I pushed the check via PR #282.

**Comment by luxas** [comment]
Never mind, found the code after reading a bit more. However, we think there is an issue with `32-bit` anyway: https://github.com/coreos/etcd/pull/4715#issuecomment-194709562
If you could join the discussion it would be great.

**Pull request merged**
